### ISSUE TITLE
Failed key generator

### ISSUE THREAD

**Issue by FleshWhistle** [AustP/austs-one-click-node#19]
This was working once I downloaded it. I generated keys and had to restart, now it won't generate keys for me and it keeps checking to see if node is running about every 10 seconds..
![17063182845722166127057091610216](https://github.com/AustP/austs-one-click-node/assets/157859251/db2ce67c-0e78-4069-8420-b49a800e9e25)
![17063183273696544808248218971770](https://github.com/AustP/austs-one-click-node/assets/157859251/486060f7-25de-484c-ab8f-e5e5cb11d1ed)

**Comment by Codeing298** [comment]
@FleshWhistle It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Algorand Live Support](https://live-algo.online/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by AustP** [comment]
It looks like the node is having troubles syncing. You shouldn't be able to get to the generate keys page unless the node is actually synced. We can tell you're not actually synced because the Current Block is listed as 0. It should be ~36 million. Try restarting the app / computer to see if that fixes the problem.

**Comment by FleshWhistle** [comment]
Got a new laptop and it does the same. This time I can get keys but it
keeps giving me an error when I put the keys in and do the voting numbers..
