### ISSUE TITLE
Feature Request: Fast Catchup + Telemetry (Voi)

### ISSUE THREAD

**Issue by 2lobo** [AustP/austs-one-click-node#5]
Voi Testnet nodes start syncing with block 0 atm (on windows at least), would be awesome if fast catchup could be a thing

Telemetry might be used to track if a node is healthy for Voi testnet so a button that would enable this would be great. Seems like the only thing that needs to be changed is the logging.config file (https://developer.algorand.org/docs/run-a-node/reference/telemetry-config/)

**Comment by AustP** [comment]
Re: Fast Catchup
Fast catchup is already enabled for Voi. The reason why no one is seeing it happen yet is because the program calculates that it is faster to just download the blocks instead of doing a catchup. Those calculations are based on Algorand block sizes and network, however, so they are most likely off but hopefully it's not too bad. Once the chain has more than 720k blocks, new users will see fast catchups starting to take place.

Re: Telemetry
I just added it in v1.3.0. Note that if you are running multiple nodes, the Voi node will have to be the "main" node (the one with the settings page) in order to configure telemetry.
