### ISSUE TITLE
Bug: Telemetry Not Enabled for Voi

### ISSUE THREAD

**Issue by bluesuedesw** [AustP/austs-one-click-node#8]
Using A1CN v1.3 on macOS 13.5.2 with both Algorand and Voi.

**Issue:** 
macOS version and potentially other platforms may not be enabling telemetry for the Voi testnet.

**Symptoms**
Updated to v1.3 to enable telemetry for the Voi health dashboard. After a few hours, noticed that telemetry for Voi was not being sent and node was not displaying on the [health dashboard](https://cswenor.github.io/voi-proposer-data/health.html) 

**Quick fix:** 
Dug into the DATA folder in Library > Application Support > A1CN > data > voi.testnet and saw the logging.config was still set to Enabled:false and name was also empty. Edited the logging.config file manually, set Enabled:true entered a name. Saved and restarted and was able to see my node on the health dashboard and telemetry is now working. 

The Algorand.mainnet telemetry was enabled as expected.

**Comment by AustP** [comment]
Hey blue, thanks for the bug report.

This is due to how I hacked in multiple node support. It only enables telemetry on the first node that you have running. In your case, it sounds like that was an Algorand node.

Thanks for the workaround so others can follow that. Hopefully I can re-engineer a better system to support multiple nodes and fix this issue with that new system.

**Comment by AustP** [comment]
v1.4.0 has been released which has better support for multi-node. You can now specify settings on each node independent of each other. After you update, make sure you check the settings on both nodes.
